"""Generate a detailed pedagogical notebook for the application."""
from __future__ import annotations
import json
from pathlib import Path

def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(True)}

def py(text: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": text.splitlines(True)}

def main() -> None:
    cells = [
        md("""# AI Insurance Data Analyst V2 — notebook pédagogique\n\nCe notebook explique bloc par bloc le code de l’application et son lien avec l’orchestration Agentic AI.\n\nPrincipe directeur : **l’IA comprend l’intention et explique ; les services déterministes calculent et modifient les données**.\n\nParcours : `CONNECT → PROFILE → CLEAN → VALIDATE → ANALYZE → EXPLAIN → VISUALIZE → REPORT → EXPORT`.\n"""),
        md("""## 1. Architecture globale\n\n```text\nUtilisateur → Streamlit/app.py → SupervisorAgent/AnalysisAgent\n                                      │\n        ┌─────────────────────────────┴─────────────────────────────┐\n        │ Ingestion │ Profiling │ Cleaning │ Analytics │ KPI │ Report │\n        └─────────────────────────────┬─────────────────────────────┘\n                                      ▼\n                           ProjectStore + AuditLogger\n\nGeminiModelManager : planification JSON et explication, jamais calcul financier.\n```\n\nUne boucle agentique observe l’état, planifie, choisit un outil autorisé, exécute, vérifie et journalise. Elle ne lance pas de Python arbitraire.\n"""),
        py("""from pathlib import Path\nimport pandas as pd\nPROJECT_ROOT = Path.cwd()\nif not (PROJECT_ROOT / 'insurance_ai').exists(): PROJECT_ROOT = PROJECT_ROOT.parent\nDATA_PATH = PROJECT_ROOT / 'sample_data' / 'insurance_sample.csv'\ndf = pd.read_csv(DATA_PATH)\nprint(len(df), 'lignes |', len(df.columns), 'colonnes')\nprint('doublons =', int(df.duplicated().sum()), '| NA =', int(df.isna().sum().sum()))\ndf.head()\n"""),
        md("""## Grandes composantes Python et utilité Agent IA\n\nLes dépendances sont organisées par responsabilité :\n\n- **Interface et état** : `streamlit` affiche les pages, widgets, messages et téléchargements ; `st.session_state` conserve la mémoire de travail du workflow.\n- **Données et calcul** : `pandas` manipule les DataFrames, `numpy` fournit les opérations numériques, `pyarrow/openpyxl/xlrd` gèrent Parquet et Excel.\n- **Visualisation** : `plotly` produit les graphiques interactifs ; `matplotlib` génère les images utilisées dans les rapports.\n- **Bases** : `sqlalchemy` abstrait les moteurs, `psycopg`, `pymysql` et `pyodbc` fournissent les connecteurs PostgreSQL, MySQL et ODBC.\n- **IA et contrats** : `google-genai` appelle Gemini ; `pydantic` et les dataclasses structurent les résultats et plans ; l’agent reste limité à des opérations allow-listées.\n- **Rapports** : `jinja2`, `reportlab`, `python-docx` et `python-pptx` alimentent les formats HTML, PDF, DOCX et PPTX.\n- **Sécurité/configuration** : `python-dotenv` charge l’environnement, `bcrypt` protège les mots de passe, `chardet` aide à détecter les encodages.\n- **Qualité** : `pytest` vérifie les parcours critiques avant déploiement.\n\nCette séparation transforme un LLM généraliste en orchestrateur d’outils spécialisés : il choisit l’outil, mais ne remplace pas les bibliothèques déterministes.\n"""),
        md("""## 2. Configuration et initialisation de `app.py`\n\n`core/config.py` construit `Settings` à partir des variables d’environnement : répertoires, taille maximale d’upload, clé Gemini, modèles autorisés, retries et timeout. Les secrets ne sont jamais codés dans l’application.\n\n`app.py` instancie `ProjectStore`, `AuditLogger`, `IngestionService`, `ProfilingService`, `CleaningService`, `DashboardService`, `ReportGenerator`, etc. `st.session_state` conserve utilisateur, projet, dataset actif et résultats entre deux reruns.\n\nLe rechargement défensif des services traite les processus Streamlit qui gardent un ancien module Python en mémoire.\n"""),
        py("""import os\nprint('APP_ENV =', os.getenv('APP_ENV', 'development'))\nprint('Gemini configuré =', bool(os.getenv('GOOGLE_API_KEY')))\nprint('Limite upload =', os.getenv('MAX_UPLOAD_MB', '200'), 'MB')\n"""),
        md("""## Mémoire de l’agent et fonctionnement Streamlit\n\nStreamlit réexécute `app.py` après une interaction. La mémoire courte est donc explicitement placée dans `st.session_state` : utilisateur, `project_id`, `df`, stade RAW/STAGING/CURATED, résultats d’analyse, graphiques et aperçu RAW.\n\nLa mémoire durable est séparée : `ProjectStore` conserve les versions de datasets et `AuditLogger` conserve les événements SQLite. `analysis_results` garde les résultats utiles au rapport, mais ce projet ne prétend pas être une mémoire conversationnelle complète : l’historique NL est structuré par résultats, pas par une conversation libre illimitée.\n\n`st.rerun()` recharge l’interface après une mutation afin que les sélecteurs, les NA et les cartes reflètent immédiatement le nouvel état. `st.cache_data` n’est pas utilisé par défaut : l’état métier doit rester explicite et éviter de mélanger les sessions.\n"""),
        md("""## 3. Ingestion et prévisualisation RAW\n\n`IngestionService` détecte encodage, séparateur et décimale des CSV, liste les feuilles Excel et aplati les JSON tabulaires. La page Importer contrôle la taille, affiche le parsing puis appelle `save_version(..., stage='RAW')`.\n\nL’aperçu RAW est conservé dans la session pour rester visible après un rerun ou un nettoyage STAGING. RAW est la copie de la source et ne doit pas être écrasé.\n"""),
        py("""from insurance_ai.services.ingestion import IngestionService\ningestion = IngestionService()\ndetection = ingestion.detect_csv(DATA_PATH.read_bytes())\nloaded, info = ingestion.read_uploaded(DATA_PATH.name, DATA_PATH.read_bytes())\nprint(detection)\nprint(info)\nloaded.head(3)\n"""),
        md("""## 4. Profilage et qualité\n\n`ProfilingService.profile(df)` calcule dimensions, types, types sémantiques, NA, cardinalité, exemples, min/max/moyenne/médiane et score qualité. Il ne modifie pas le DataFrame.\n\nLes règles métier (`not_null`, `unique`, `non_negative`, `allowed_values`, `date_order`) évaluent les violations et peuvent alimenter un rapport.\n"""),
        py("""from insurance_ai.services.profiling import ProfilingService\nprofile = ProfilingService().profile(df)\nprint(profile.summary)\nprint('doublons =', profile.duplicate_rows)\nprofile.columns[['column', 'missing', 'missing_pct', 'semantic_type']]\n"""),
        md("""## 5. Nettoyage et imputation cellule par cellule\n\n`CleaningService` expose normalisation, déduplication, cast, catégories, filtres et imputation. L’UI liste dynamiquement les variables avec NA, sélectionne une ligne, choisit une stratégie puis appelle `impute_cell`. Après chaque action, Streamlit rerun, recalcule les NA et écrit un `TransformationRecord`.\n\nLes identifiants potentiels ne peuvent recevoir qu’une valeur manuelle vérifiée : une moyenne ne doit jamais inventer une clé de police ou de sinistre.\n"""),
        py("""from insurance_ai.services.cleaning import CleaningService\ncleaner = CleaningService()\npositions = [i for i, missing in enumerate(df['region'].isna()) if missing]\noutcome = cleaner.impute_cell(df, 'region', positions[0], 'manual', 'Abidjan')\nprint(outcome.details)\nprint('NA avant/après =', df.region.isna().sum(), outcome.dataframe.region.isna().sum())\n"""),
        md("""## 6. Versions RAW / STAGING / CURATED\n\n`ProjectStore` écrit les datasets dans un projet et conserve source, stade, parent, dimensions, empreinte et chemin relatif. RAW conserve la source ; STAGING porte les transformations ; CURATED est la version validée et autorisée pour les analyses.\n"""),
        py("""from tempfile import TemporaryDirectory\nfrom insurance_ai.core.project_store import ProjectStore\nwith TemporaryDirectory() as folder:\n    store = ProjectStore(folder)\n    project_id = store.create_project('Notebook', owner='demo')\n    raw_meta = store.save_dataframe(project_id, df, name='sample', stage='RAW', source_type='csv', source_name=DATA_PATH.name)\n    print(raw_meta.to_dict())\n"""),
        md("""## 7. KPI assurance déterministes\n\n`InsuranceKPIService` calcule S/P, coût moyen, fréquence, encaissement, cession et rétention. Les résultats contiennent valeur, formule et avertissements ; les dénominateurs nuls sont traités. Gemini ne produit jamais ces chiffres.\n"""),
        py("""from insurance_ai.services.insurance_kpi import InsuranceKPIService\nkpis = InsuranceKPIService()\nloss_ratio = kpis.loss_ratio(df, 'claim_amount', 'written_premium')\nprint(loss_ratio)\nprint(kpis.as_display(loss_ratio))\n"""),
        md("""## 8. Dashboard sur RAW et CURATED\n\n`DashboardService.metric_columns` filtre selon le sens métier : primes (`written_premium`, `collected_premium`, `ceded_premium`, `net_premium`) et sinistres (`claim_amount`, coûts ou montants). Les identifiants sont exclus.\n\nLe même service reçoit le DataFrame RAW ou CURATED actif et produit cartes KPI, segments, tendances et principaux sinistres.\n"""),
        py("""from insurance_ai.services.dashboard import DashboardService\ndashboard = DashboardService()\npremium_cols = dashboard.metric_columns(df, 'premium')\nclaim_cols = dashboard.metric_columns(df, 'claims')\nprint('primes =', premium_cols)\nprint('sinistres =', claim_cols)\nview = dashboard.portfolio_overview(df, premium_col=premium_cols[0], claims_col=claim_cols[0], group_col='branch', date_col='effective_date')\nview.cards\n"""),
        md("""## 9. Analytics allow-listées\n\n`AnalyticsService.OPS` autorise seulement description, comptage, agrégations, top valeurs et corrélations. Les filtres sont limités à `==`, `!=`, `>`, `>=`, `<`, `<=`, `contains`.\n\nMême si Gemini propose un plan invalide, `_validate_plan` le rejette avant exécution. Aucun `eval()`/`exec()` n’est utilisé.\n"""),
        py("""from insurance_ai.services.analytics import AnalyticsService\nanalytics = AnalyticsService()\nresult = analytics.execute(df, {'operation': 'mean', 'column': 'written_premium', 'filters': []})\nprint(result.answer)\nprint(result.calculation)\n"""),
        md("""## 10. SupervisorAgent et AnalysisAgent\n\n`SupervisorAgent.route()` choisit profilage, nettoyage ou analyse. `AnalysisAgent` résume le schéma, demande éventuellement à Gemini un plan JSON, valide opération/colonnes/filtres puis délègue à `AnalyticsService`.\n\nSans clé Gemini, une heuristique offline reconnaît moyenne, somme, corrélation, top valeurs et description. Avec Gemini, seul le plan est généré ; Pandas calcule.\n"""),
        py("""from insurance_ai.agents.supervisor import SupervisorAgent\nsupervisor = SupervisorAgent()\nprint(supervisor.route('analyze'))\nanswer, plan = supervisor.ask('Quelle est la moyenne de written_premium ?', df)\nprint('plan =', plan)\nprint('résultat =', answer.data)\nprint('calcul =', answer.calculation)\n"""),
        md("""## 11. GeminiModelManager : fallback et gouvernance\n\nLe gestionnaire centralise timeout, retries avec backoff, modèles de secours et latence. `generate_json` parse les plans. Si tous les modèles échouent, qualité, nettoyage, KPI, dashboard et reporting restent disponibles.\n\nLe prompt reçoit un résumé de schéma plutôt que le dataset complet ; l’explication reçoit un résultat compact et doit mentionner la méthode sans inventer de nombres.\n"""),
        md("""## 12. Reporting, audit et sécurité\n\n`ReportPayload` alimente les rendus HTML/PDF/DOCX/PPTX/XLSX. `AuditLogger` journalise transformations, analyses et exports dans SQLite avec requêtes paramétrées.\n\nGarde-fous : secrets hors Git, uploads limités, SQL lecture seule, chemins confinés, RAW préservé, identifiants protégés, opérations NL allow-listées et séparation logique des projets.\n"""),
        py("""from insurance_ai.core.models import TransformationRecord\nrecord = TransformationRecord(transformation_id='demo-001', dataset_id='raw-demo', operation='impute_cell', column='region', parameters={'row_position': 9, 'strategy': 'manual', 'value': 'Abidjan'}, rows_before=len(df), rows_after=len(df), user='demo')\nrecord.to_dict()\n"""),
        md("""## 13. Flux complet Agentic AI\n\n```text\nQuestion → observation du schéma/session → plan JSON\n        → validation allow-list → outil Pandas/KPI/dashboard\n        → résultat déterministe → explication Gemini\n        → audit + ajout éventuel au rapport\n```\n\nLa valeur agentique vient de la coordination des outils et de la gestion de l’état. La sécurité vient de la validation avant l’action. Une évolution possible est de séparer des agents Ingestion, Qualité, Assurance, Visualisation et Reporting en conservant les mêmes contrats déterministes.\n"""),
        md("""## Références du dépôt\n\n- `app.py` : UI Streamlit, session et parcours utilisateur\n- `insurance_ai/agents/analysis_agent.py` : planification/explanation NL\n- `insurance_ai/agents/supervisor.py` : routage\n- `insurance_ai/services/analytics.py` : opérations allow-listées\n- `insurance_ai/services/gemini_manager.py` : fallback Gemini\n- `insurance_ai/core/project_store.py` : versions RAW/STAGING/CURATED\n- `insurance_ai/core/audit.py` : audit SQLite\n- `docs/ARCHITECTURE.md`, `docs/SECURITY.md`, `docs/MOA_TRACEABILITY.md` : documentation de référence\n"""),
    ]
    notebook = {'cells': cells, 'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}, 'language_info': {'name': 'python'}}, 'nbformat': 4, 'nbformat_minor': 5}
    destination = Path(__file__).resolve().parents[1] / 'docs' / 'AI_Insurance_Data_Analyst_Pedagogical.ipynb'
    destination.write_text(json.dumps(notebook, ensure_ascii=False, indent=1), encoding='utf-8')
    print(destination)

if __name__ == '__main__':
    main()
